export const governorateArr: { value: string, option: string }[] = [
    { value: "SU", option: "6th of October" },
    { value: "SHR", option: "Al Sharqia" },
    { value: "ALX", option: "Alexandria" },
    { value: "ASN", option: "Aswan" },
    { value: "AST", option: "Asyut" },
    { value: "BH", option: "Beheira" },
    { value: "BNS", option: "Beni Suef" },
    { value: "C", option: "Cairo" },
    { value: "DK", option: "Dakahlia" },
    { value: "DT", option: "Damietta" },
    { value: "FYM", option: "Faiyum" },
    { value: "GH", option: "Gharbia" },
    { value: "GZ", option: "Giza" },
    { value: "HU", option: "Helwan" },
    { value: "IS", option: "Ismailia" },
    { value: "KFS", option: "Kafr el-Sheikh" },
    { value: "LX", option: "Luxor" },
    { value: "MT", option: "Matrouh" },
    { value: "MN", option: "Minya" },
    { value: "MNF", option: "Monufia" },
    { value: "WAD", option: "New Valley" },
    { value: "SIN", option: "North Sinai" },
    { value: "PTS", option: "Port Said" },
    { value: "KN", option: "Qena" },
    { value: "BA", option: "Red Sea" },
    { value: "SHG", option: "Sohag" },
    { value: "JS", option: "South Sinai" },
    { value: "SUZ", option: "Suez" },
];
