
export const shippingMethodArr: { value: string, id: string, price: number }[] = [
    { value: "Cairo & Giza", id: "exampleRadios", price: 50 },
    { value: "Alexandria", id: "exampleRadios1", price: 55 },
    { value: "Behira", id: "exampleRadios2", price: 55 },
    { value: "Sahel", id: "exampleRadios3", price: 55 },
    { value: "Dakahlia", id: "exampleRadios4", price: 60 },
    { value: "Damietta", id: "exampleRadios5", price: 60 },
    { value: "El Kalioubia", id: "exampleRadios6", price: 60 },
    { value: "Gharbia", id: "exampleRadios7", price: 60 },
    { value: "Ismailia", id: "exampleRadios8", price: 60 },
    { value: "Kafr El-Sheikh", id: "exampleRadios9", price: 60 },
    { value: "Monufia", id: "exampleRadios10", price: 60 },
    { value: "Port Said", id: "exampleRadios11", price: 60 },
    { value: "Sharqia", id: "exampleRadios12", price: 60 },
    { value: "Suez", id: "exampleRadios13", price: 60 },
    { value: "Assiut", id: "exampleRadios14", price: 70 },
    { value: "Beni Suef", id: "exampleRadios15", price: 70 },
    { value: "Fayoum", id: "exampleRadios16", price: 70 },
    { value: "Menya", id: "exampleRadios17", price: 70 },
    { value: "Sohag", id: "exampleRadios18", price: 70 },
    { value: "Aswan", id: "exampleRadios19", price: 85 },
    { value: "Luxor", id: "exampleRadios20", price: 85 },
    { value: "Matrouh", id: "exampleRadios21", price: 85 },
    { value: "North Coast", id: "exampleRadios22", price: 85 },
    { value: "Qena", id: "exampleRadios23", price: 85 },
    { value: "Red Sea", id: "exampleRadios24", price: 85 },
    { value: "New Valley", id: "exampleRadios25", price: 90 },
    { value: "North Sinai", id: "exampleRadios26", price: 90 },
    { value: "South Sinai", id: "exampleRadios27", price: 90 },
];